### ISSUE TITLE
Messed up graphics in Lovecraft ending

### ISSUE THREAD

**Issue by Kapow751** [segrax/DrCreep#10]
The base of the leftmost tree in the Lovecraft ending is shorter than the rest, and the top is in the wrong place (behind the "TIME" text) with weird colors. Also, the rightmost tree was originally cut off by the edge of the screen, but the screen now extends past it, so the edge of the treetop appears to be floating in midair.

Current version: https://i.imgur.com/h9uBNja.png

C64 version (from youtube): https://i.imgur.com/LH8taTe.png

**Comment by segrax** [comment]
Thanks!

Have just pushed out the fix
