### ISSUE TITLE
Game not starting (crash with no error message)

### ISSUE THREAD

**Issue by boweden** [segrax/DrCreep#11]
Hello, I installed the game (v1.2.1) on Windows 10 x64 using the provided VC++ 2017 redistributable (and I tried different versions of VC++ for both x86 and x64).

When I start the game, I get no response.  No error messages.  The mouse cursor gets busy but then nothing happens.

Looking into the Windows Event Viewer log, I noticed the following error:

> Faulting application name: creep.exe, version: 0.0.0.0, time stamp: 0x5e76f0bc
> Faulting module name: VCRUNTIME140.dll, version: 14.26.28720.3, time stamp: 0x5e74ae97
> Exception code: 0xc0000005
> Fault offset: 0x000033a0
> Faulting process id: 0x898
> Faulting application start time: 0x01d64754d389dac8
> Faulting application path: C:\Games\DrCreep\creep.exe
> Faulting module path: C:\Windows\SYSTEM32\VCRUNTIME140.dll
> Report Id: a1e14812-90f9-429e-8345-5f4ee34f0405
> Faulting package full name: 
> Faulting package-relative application ID: 

Does this indicate a bug in the program (the exception code seems to be some memory access violation) or am I missing some prerequisite?

Thank you

[edit] the VC++ runtime I used here is 2019 (version 14.26.28720.3), but I had the same error with VC++ 2017 (version 14.11.25325.0)

**Comment by boweden** [comment]
Ah, it seems the problem is with the D64 that was used.  It seems the game supports only the one with a CRC checksum of "56A7F7FA".  Other versions will produce a crash.

**Comment by boweden** [comment]
... and it seems the reason v1.2.1 doesn't work is because certain files from the earlier version (joystick.bmp, keyboard.bmp and possibly even SDL2_mixer.dll ??? ) were not included in the newer version

**Comment by segrax** [comment]
Haha opps,

Try 1.3
https://github.com/segrax/DrCreep/releases/tag/1.3

**Comment by boweden** [comment]
Thanks for the update.  Seems to work now, although SDL2_mixer.dll is still missing.  Is that file not needed anymore?

**Comment by segrax** [comment]
Yeah, 
I can't recall if it ever was actually needed or just included by mistake, but it isn't now (perhaps sdl1 leftover?)

There is a couple of disk versions which do work, but most of the cracked versions I've tried over time do not (reasons vary, but largely filename differences/packed files)

heres some CRC from working versions ive got

03E1C09C (Blade Runner crack)
56A7F7FA (Original)
EF704DD5 (Original - is modified)

**Comment by segrax** [comment]
Oh, it also works with "Dungeons of Doctor Creep (1985)"

**Comment by boweden** [comment]
Thanks a lot for clarifying, especially also for your diligence in providing support and keeping the game bug-free.
