### ISSUE TITLE
Hitbox bug makes Rittenhouse impossible

### ISSUE THREAD

**Issue by Kapow751** [segrax/DrCreep#5]
The far left light blue room in Rittenhouse has a red matter transmitter oval very close to a lightning machine to the left. If you teleport there, you die immediately, making the top-right door inaccessible. This does not happen on the C64 version.

Steam thread with more info, including a video of the C64 version: https://steamcommunity.com/app/517930/discussions/0/135512931362059688/

**Comment by Kapow751** [comment]
This also seems to affect Teasdale, in the room left of center there's an ankh just to the right of a tomb, if you walk too far onto it you get hit by the mummy as it spawns. In the C64 version, you can walk onto the ankh and take the pole immediately without getting hit: https://youtu.be/poIRsqT8ED8?t=225

In this case, death can be avoided by touching the edge of the ankh and waiting a fraction of a second for the mummy to slide partway out, but the timing is tight to get past before the mummy attacks.

**Comment by segrax** [comment]
Thanks for opening this,

Apologies for the delay,
Hadn't seen the thread on Steam, seems i haven't been receiving notifications about forum posts.

Anyway, I've just pushed a fix to GitHub and deployed a new bundle on steam which solves the problem
