### ISSUE TITLE
Text spacing is incorrect, text covers tutorial elements

### ISSUE THREAD

**Issue by Kapow751** [segrax/DrCreep#6]
The spacing between text lines seems to be 1 pixel too tall, which causes issues with the tutorial and the instructions at the bottom of the Best Times screen.

Current version: https://i.imgur.com/UdzMXTT.png https://i.imgur.com/Mqels6t.png

C64 version (from youtube): https://i.imgur.com/kCwvhpC.png https://i.imgur.com/zDmPxx5.png

**Comment by segrax** [comment]
Fixed,
also takes care of the TIME on end screen
