### ISSUE TITLE
Road is missing from "escaped" ending screen

### ISSUE THREAD

**Issue by Kapow751** [segrax/DrCreep#7]
The screen after escaping a castle is supposed to have a gray background with a brown road the player walks along. I think this is part of every ending screen, appearing behind the unique graphical elements for each castle.

Also, minor issue but the positioning of the "TIME:" text seems to be inconsistent between castles.

Current version: https://i.imgur.com/L6o7nHe.png https://i.imgur.com/tixIeBO.png

C64 version (from youtube): https://i.imgur.com/JXklkpg.png https://i.imgur.com/0JuDSAi.png

**Comment by segrax** [comment]
Wow, nice pickup!

Thanks, is now fixed, will be in the release done later tonight
