### ISSUE TITLE
Wrong level order in Steam version, levels are misspelled

### ISSUE THREAD

**Issue by Kapow751** [segrax/DrCreep#9]
Not sure if this only applies to the Steam version, but that has the levels listed in alphabetical order after Tutorial, which means people are starting with Alternation and Baskerville. Originally, the easiest levels are near the top and the hardest are mostly at the end.

The original order is: https://i.imgur.com/ncYidmg.png
Tutorial, Sylvania,
Callanwolde, Tannenbaum,
Alternation, Freedonia,
Carpathia, Parthenia,
Teasdale, Rittenhouse,
Romania, Doublecross,
Baskerville, Lovecraft

Also, Parthenia is misspelled as "Pathenia" in the game and the Steam achievement, and the Steam achievement for Callanwolde is misspelled "Callenwolde".

**Comment by segrax** [comment]
Thanks,

Also now fixed. The original game used the order of the castles as on disk (or in D64 in the opensource build), whereas the steam version used the order given by the operating system

Have just pushed a new build to Steam,
Cheers!
